apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-local
  labels:
    app: myapp-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-local
  template:
    metadata:
      name: myapp-pod-local
      labels:
        app: myapp-local
    spec:
      containers:
      - name: myapp-container
        image: ewoutp/docker-nginx-curl
        ports:
          - containerPort: 80
        env:
          - name: TEST
            value: "20"
        volumeMounts:
          - name: mysql
            mountPath: /usr/local/nginx/html
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: local01
