apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    app: local01
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfs/general/01
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle

