apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      name: python-pod
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: marcinmakowski/python-api:redis
        ports:
          - containerPort: 5002
        env:
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
