apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-actor-pv-claim
  namespace: rl-platform
  labels: 
    project: rl-platform
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "3Gi"