apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    app: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfs/general/01
    server: kmaster1
  persistentVolumeReclaimPolicy: Recycle
  