apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0000
  labels:
    app: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfs/general/00
    server: 172.18.126.9
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1

