apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
  name: python
  namespace: default
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: python
  type: NodePort
