apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-24T14:42:59Z"
  labels:
    app: registry
  name: registry
  namespace: default
  resourceVersion: "43047"
  selfLink: /api/v1/namespaces/default/services/registry
  uid: 2a0f884c-b6b2-4add-8260-7db0e37076f2
spec:
  clusterIP: 10.110.31.11
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30580
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
