apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    app: pv0003
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    path: /var/nfs/general/03
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
  labels:
    app: pv0004
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nfs:
    path: /var/nfs/general/04
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle


