apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: default  
spec:
  ports:
  - nodePort: 31690
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
  type: NodePort