apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podcreators.bash-operators.maque
spec:
  group: bash-operators.maque
  version: v1alpha1
  names:
    kind: PodCreator
    plural: podcreators
  scope: Namespaced
