kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod.operator.role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["apiextensions.k8s.io/v1beta1"] # "" indicates the core API group
  resources: ["podcreators"]
  verbs: ["get", "watch", "list"]