apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local01
  labels:
    app: local01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local02
  labels:
    app: local02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi