apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqrt
  name: sqrt-generator
  namespace: default  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sqrt
  type: ClusterIP